[package]
name = "toy-ray-tracer-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["toy_ray_tracer"]

[lib]
crate-type = ["cdylib"]

[dependencies]
# gdnative = "0.10"

